sudo: required

services:
- docker

jobs:
  include:
  - stage: Test
    script:
    - npm install && npm run test
  - stage: Deploy
    if: (branch = master) AND (type = push)
    provider: heroku
    script: "./deploy.sh"